# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_display = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_display.setGeometry(QtCore.QRect(20, 100, 761, 441))
        self.output_display.setObjectName("output_display")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 131, 61))
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.inputfile_button = QtWidgets.QPushButton(self.centralwidget)
        self.inputfile_button.setEnabled(True)
        self.inputfile_button.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.inputfile_button.setObjectName("inputfile_button")
        self.filename_display = QtWidgets.QLabel(self.centralwidget)
        self.filename_display.setEnabled(True)
        self.filename_display.setGeometry(QtCore.QRect(30, 70, 751, 16))
        self.filename_display.setObjectName("filename_display")
        self.inputview_button = QtWidgets.QPushButton(self.centralwidget)
        self.inputview_button.setEnabled(False)
        self.inputview_button.setGeometry(QtCore.QRect(260, 40, 75, 23))
        self.inputview_button.setObjectName("inputview_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Unicode character counter"))
        self.label.setText(_translate("MainWindow", "Count unicode characters"))
        self.inputfile_button.setText(_translate("MainWindow", "Open file"))
        self.filename_display.setText(_translate("MainWindow", "TextLabel"))
        self.inputview_button.setText(_translate("MainWindow", "View input"))
